# Generated by Django 4.2.7 on 2023-11-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, unique=True)),
                ('tournament_name', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=32, unique=True)),
                ('event_season', models.CharField(max_length=32)),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('fencer_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('competitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.fencer')),
                ('event_placed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.event')),
            ],
        ),
    ]
